<a href="https://colab.research.google.com/github/stela92s/aurora-siger-pre-decolagem/blob/main/5_aurora_siger.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Telemetria

In [14]:
import random
from datetime import datetime


# 1. INICIALIZAÇÃO
def inicializacao():
    print("==================================================")
    print("1. INICIALIZAÇÃO DO SISTEMA")
    print("==================================================")
    print("Sistema iniciado com sucesso.")
    print()


# 2. RECEBIMENTO DOS DADOS
def dados_telemetria():
    return {
        "DATA": datetime.now().strftime("%d/%m/%Y"),
        "T_INT": round(random.uniform(10, 35), 2),
        "T_EXT": round(random.uniform(-60, 60), 2),
        "STR": random.randint(0, 1),
        "PWR": round(random.uniform(50, 100), 2),
        "PRS": round(random.uniform(100, 350), 2),
        "MOD": random.choice(["OK", "FALHA"])
    }


def exibir_telemetria(dados):
    print("==================================================")
    print("2. RECEBIMENTO DOS DADOS")
    print("==================================================")
    print()

    print(f"Data: {dados['DATA']}")
    print(f"Temperatura interna: {dados['T_INT']} °C")
    print(f"Temperatura externa: {dados['T_EXT']} °C")
    print(f"Integridade estrutural: {dados['STR']}")
    print(f"Nível de energia: {dados['PWR']}%")
    print(f"Pressão dos tanques: {dados['PRS']}")
    print(f"Módulos críticos: {dados['MOD']}")
    print()


# 3. VALIDAÇÃO DOS PARÂMETROS
def validar_parametros(dados):
    print("==================================================")
    print("3. VALIDAÇÃO DOS PARÂMETROS")
    print("==================================================")
    print()

    falhas = []
    sistema_ok = True

    # Temperatura interna
    if 15 <= dados["T_INT"] <= 30:
        print("Temperatura interna: OK")
    else:
        print("Temperatura interna: NOK")
        falhas.append("Temperatura interna")
        sistema_ok = False

    # Temperatura externa
    if -50 <= dados["T_EXT"] <= 50:
        print("Temperatura externa: OK")
    else:
        print("Temperatura externa: NOK")
        falhas.append("Temperatura externa")
        sistema_ok = False

    # Integridade estrutural
    if dados["STR"] == 1:
        print("Integridade estrutural: OK")
    else:
        print("Integridade estrutural: NOK")
        falhas.append("Integridade estrutural")
        sistema_ok = False

    # Nível de energia
    if 80 <= dados["PWR"] <= 100:
        print("Nível de energia: OK")
    else:
        print("Nível de energia: NOK")
        falhas.append("Nível de energia")
        sistema_ok = False

    # Pressão dos tanques
    if 150 <= dados["PRS"] <= 300:
        print("Pressão dos tanques: OK")
    else:
        print("Pressão dos tanques: NOK")
        falhas.append("Pressão dos tanques")
        sistema_ok = False

    # Módulos críticos
    if dados["MOD"] == "OK":
        print("Módulos críticos: OK")
    else:
        print("Módulos críticos: NOK")
        falhas.append("Módulos críticos")
        sistema_ok = False

    return sistema_ok, falhas


# 4. DECISÃO FINAL
def decisao_final(sistema_ok, falhas):
    print()
    print("==================================================")
    print("4. DECISÃO FINAL")
    print("==================================================")
    print()

    if sistema_ok:
        print("STATUS: DECOLAR")
    else:
        print(f"Número de falhas: {len(falhas)}")
        print()
        print("Falhas identificadas:")

        for falha in falhas:
            print(f"- {falha}")

        print()
        print("STATUS: ABORTAR")


# ==================================================
# PROGRAMA PRINCIPAL
# ==================================================

# 1. Inicialização
inicializacao()

# 2. Recebimento dos dados
dados_telemetria_atual = dados_telemetria()
exibir_telemetria(dados_telemetria_atual)

# 3. Validação dos parâmetros
sistema_ok, falhas = validar_parametros(dados_telemetria_atual)

# 4. Decisão final
decisao_final(sistema_ok, falhas)

==================================================
1. INICIALIZAÇÃO DO SISTEMA
==================================================
Sistema iniciado com sucesso.

==================================================
2. RECEBIMENTO DOS DADOS
==================================================

Data: 16/09/2026
Temperatura interna: 17.56 °C
Temperatura externa: 48.03 °C
Integridade estrutural: 1
Nível de energia: 88.58%
Pressão dos tanques: 101.45
Módulos críticos: FALHA

==================================================
3. VALIDAÇÃO DOS PARÂMETROS
==================================================

Temperatura interna: OK
Temperatura externa: OK
Integridade estrutural: OK
Nível de energia: OK
Pressão dos tanques: NOK
Módulos críticos: NOK

==================================================
4. DECISÃO FINAL
==================================================

Número de falhas: 2

Falhas identificadas:
- Pressão dos tanques
- Módulos críticos

STATUS: ABORTAR

# Análise energética

In [15]:
import random


# 1. INICIALIZAÇÃO
def inicializacao():

    print("==================================================")
    print("1. INICIALIZAÇÃO")
    print("==================================================")
    print()
    print("INICIAR sistema de análise energética")
    print()


# 2. DADOS ENERGÉTICOS
def dados_energia():
    return {
        "capacidade_total": round(random.uniform(50, 100), 2),
        "carga_atual": round(random.uniform(50, 100), 2),
        "consumo": round(random.uniform(15, 40), 2),
        "perdas_energeticas": round(random.uniform(5, 15), 2)
    }


def exibir_energia(dados):

    print("==================================================")
    print("2. DADOS ENERGÉTICOS")
    print("==================================================")
    print()

    print(f"Capacidade total:       {dados['capacidade_total']} kWh")
    print(f"Carga atual:            {dados['carga_atual']} %")
    print(f"Consumo médio:          {dados['consumo']} kW")
    print(f"Perdas energéticas:     {dados['perdas_energeticas']} %")
    print()


# 3. ANÁLISE ENERGÉTICA
def validar_parametros(dados):

    capacidade_total = dados["capacidade_total"]
    carga_atual = dados["carga_atual"]
    consumo = dados["consumo"]
    perdas_percentual = dados["perdas_energeticas"]

    # Calcula a energia disponível
    energia_disponivel = capacidade_total * (carga_atual / 100)

    # Calcula as perdas
    perdas = energia_disponivel * (perdas_percentual / 100)

    # Calcula a energia útil
    energia_util = energia_disponivel - perdas

    # Calcula a autonomia em horas
    autonomia = energia_util / consumo

    # Converte a autonomia para minutos
    autonomia_minutos = autonomia * 60

    return {
        "energia_disponivel": round(energia_disponivel, 2),
        "perdas": round(perdas, 2),
        "energia_util": round(energia_util, 2),
        "autonomia": round(autonomia, 2),
        "autonomia_minutos": round(autonomia_minutos, 2)
    }


def imprimir_analise(analise):

    print("==================================================")
    print("3. ANÁLISE ENERGÉTICA")
    print("==================================================")
    print()

    print(f"Energia disponível:    {analise['energia_disponivel']} kWh")
    print(f"Perdas energéticas:    {analise['perdas']} kWh")
    print(f"Energia útil:          {analise['energia_util']} kWh")
    print(f"Autonomia estimada:    {analise['autonomia']} h")
    print(f"Autonomia estimada:    {analise['autonomia_minutos']} min")
    print()


# 4. DECISÃO FINAL
AUTONOMIA_MINIMA = 2.0


def gerar_resultado(analise):

    autonomia = analise["autonomia"]

    if autonomia >= AUTONOMIA_MINIMA:
        status = "OK"
        mensagem = "Condição energética adequada para a operação."
    else:
        status = "NOK"
        mensagem = "Condição energética insuficiente para a operação."

    resultado = {
        "status": status,
        "mensagem": mensagem,
        "autonomia_minima": AUTONOMIA_MINIMA
    }

    return resultado


def imprimir_resultado(resultado):

    print("==================================================")
    print("4. DECISÃO FINAL")
    print("==================================================")
    print()

    print(f"Autonomia mínima:      {resultado['autonomia_minima']} h")
    print(f"Condição energética:   {resultado['status']}")
    print(f"Status:                 {resultado['mensagem']}")
    print()


# ==================================================
# PROGRAMA PRINCIPAL
# ==================================================

# 1. INICIALIZAÇÃO
inicializacao()

# 2. DADOS ENERGÉTICOS
dados_energia_atual = dados_energia()
exibir_energia(dados_energia_atual)

# 3. ANÁLISE ENERGÉTICA
analise = validar_parametros(dados_energia_atual)
imprimir_analise(analise)

# 4. DECISÃO FINAL
resultado = gerar_resultado(analise)
imprimir_resultado(resultado)

==================================================
1. INICIALIZAÇÃO
==================================================

INICIAR sistema de análise energética

==================================================
2. DADOS ENERGÉTICOS
==================================================

Capacidade total:       58.59 kWh
Carga atual:            62.99 %
Consumo médio:          36.31 kW
Perdas energéticas:     6.97 %

==================================================
3. ANÁLISE ENERGÉTICA
==================================================

Energia disponível:    36.91 kWh
Perdas energéticas:    2.57 kWh
Energia útil:          34.33 kWh
Autonomia estimada:    0.95 h
Autonomia estimada:    56.73 min

==================================================
4. DECISÃO FINAL
==================================================

Autonomia mínima:      2.0 h
Condição energética:   NOK
Status:                 Condição energética insuficiente para a operação.

# IA

In [16]:
# ==================================================
# 5. ANÁLISE ASSISTIDA POR IA
# ==================================================

def preparar_dados_para_ia():

    dados_ia = {
        "telemetria": {
            "temperatura_interna": dados_telemetria_atual["T_INT"],
            "temperatura_externa": dados_telemetria_atual["T_EXT"],
            "integridade_estrutural": dados_telemetria_atual["STR"],
            "nivel_energia": dados_telemetria_atual["PWR"],
            "pressao_tanques": dados_telemetria_atual["PRS"],
            "modulos_criticos": dados_telemetria_atual["MOD"],
            "status_sistema": "OK" if sistema_ok else "NOK",
            "falhas": falhas
        },

        "energia": {
            "energia_disponivel": analise["energia_disponivel"],
            "perdas": analise["perdas"],
            "energia_util": analise["energia_util"],
            "autonomia": analise["autonomia"],
            "autonomia_minima": resultado["autonomia_minima"],
            "status_energia": resultado["status"]
        }
    }

    return dados_ia


dados_ia = preparar_dados_para_ia()

print("==================================================")
print("5. DADOS ENVIADOS PARA A IA")
print("==================================================")
print()

print("TELEMETRIA:")
print(dados_ia["telemetria"])

print()
print("ANÁLISE ENERGÉTICA:")
print(dados_ia["energia"])

==================================================
5. DADOS ENVIADOS PARA A IA
==================================================

TELEMETRIA:
{'temperatura_interna': 17.56, 'temperatura_externa': 48.03, 'integridade_estrutural': 1, 'nivel_energia': 88.58, 'pressao_tanques': 101.45, 'modulos_criticos': 'FALHA', 'status_sistema': 'NOK', 'falhas': ['Pressão dos tanques', 'Módulos críticos']}

ANÁLISE ENERGÉTICA:
{'energia_disponivel': 36.91, 'perdas': 2.57, 'energia_util': 34.33, 'autonomia': 0.95, 'autonomia_minima': 2.0, 'status_energia': 'NOK'}

In [45]:
!pip install -q transformers torch
!pip install -q -U transformers accelerate

In [46]:
import torch

print("GPU disponível:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
else:
    print("Executando pela CPU")

GPU disponível: False
Executando pela CPU

In [47]:
from transformers import AutoTokenizer, AutoModelForCausalLM

MODELO = "Qwen/Qwen2.5-1.5B-Instruct"

print("Carregando modelo de IA...")

tokenizer = AutoTokenizer.from_pretrained(MODELO)

model = AutoModelForCausalLM.from_pretrained(
    MODELO,
    torch_dtype="auto",
    device_map="auto"
)

print("IA carregada com sucesso!")

Carregando modelo de IA...

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/660 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/7.30k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/2.78M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/1.67M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/7.03M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 3.09GB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

IA carregada com sucesso!

In [ ]:
import json
import torch
from IPython.display import display
import pandas as pd

# ==========================================================
# 5. PREPARAÇÃO DOS DADOS PARA A IA
# ==========================================================

dados_formatados = json.dumps(
    dados_ia,
    ensure_ascii=False,
    indent=2
)

# ==========================================================
# 6. TABELA DE TELEMETRIA
# ==========================================================

print("=" * 60)
print("6. TELEMETRIA DA AURORA SIGER")
print("=" * 60)

tabela_telemetria = pd.DataFrame([
    ["Temperatura interna", dados_ia["telemetria"]["temperatura_interna"], "°C"],
    ["Temperatura externa", dados_ia["telemetria"]["temperatura_externa"], "°C"],
    ["Integridade estrutural", dados_ia["telemetria"]["integridade_estrutural"], ""],
    ["Nível de energia", dados_ia["telemetria"]["nivel_energia"], "%"],
    ["Pressão dos tanques", dados_ia["telemetria"]["pressao_tanques"], ""],
    ["Módulos críticos", dados_ia["telemetria"]["modulos_criticos"], ""],
    ["Status do sistema", dados_ia["telemetria"]["status_sistema"], ""],
], columns=["Parâmetro", "Valor", "Unidade"])

display(tabela_telemetria)


# ==========================================================
# 7. DIAGNÓSTICO DA TELEMETRIA
# ==========================================================

print()
print("DIAGNÓSTICO DA TELEMETRIA")
print("-" * 60)

if dados_ia["telemetria"]["status_sistema"] == "OK":
    print("O sistema de telemetria não apresenta falhas identificadas.")
else:
    print("Foram identificadas condições que exigem atenção.")

if dados_ia["telemetria"]["falhas"]:
    print()
    print("Falhas identificadas:")
    for falha in dados_ia["telemetria"]["falhas"]:
        print(f"- {falha}")
else:
    print("Nenhuma falha foi registrada.")


# ==========================================================
# 8. TABELA ENERGÉTICA
# ==========================================================

print()
print("=" * 60)
print("8. ANÁLISE ENERGÉTICA")
print("=" * 60)

tabela_energia = pd.DataFrame([
    ["Energia disponível", dados_ia["energia"]["energia_disponivel"], "kWh"],
    ["Perdas energéticas", dados_ia["energia"]["perdas"], "kWh"],
    ["Energia útil", dados_ia["energia"]["energia_util"], "kWh"],
    ["Autonomia estimada", dados_ia["energia"]["autonomia"], "h"],
    ["Autonomia mínima", dados_ia["energia"]["autonomia_minima"], "h"],
    ["Status energético", dados_ia["energia"]["status_energia"], ""],
], columns=["Parâmetro", "Valor", "Unidade"])

display(tabela_energia)


# ==========================================================
# 9. DIAGNÓSTICO ENERGÉTICO
# ==========================================================

print()
print("DIAGNÓSTICO ENERGÉTICO")
print("-" * 60)

if dados_ia["energia"]["status_energia"] == "OK":
    print("A condição energética está adequada para a operação.")
else:
    print("A condição energética apresenta insuficiência de autonomia.")


# ==========================================================
# 10. IA - ANÁLISE INTELIGENTE
# ==========================================================

mensagens = [
    {
        "role": "system",
        "content": """
Você é a inteligência artificial de análise da nave espacial Aurora Siger.

Analise os dados de telemetria e energia fornecidos.

Sua análise deve ser baseada SOMENTE nos dados recebidos.
Não invente valores.
Não altere os valores.
Não crie falhas que não estejam relacionadas aos dados.

Divida sua resposta obrigatoriamente em três partes:

CLASSIFICAÇÃO DOS DADOS
Classifique a situação geral dos dados como:
- NORMAL
- ATENÇÃO
- CRÍTICO

Explique brevemente o motivo.

IDENTIFICAÇÃO DE POSSÍVEIS ANOMALIAS
Identifique os parâmetros que estejam fora das condições esperadas ou que mereçam atenção.
Explique o motivo de cada possível anomalia.

SUGESTÕES DE RISCO
Apresente riscos potenciais relacionados aos dados encontrados.
As sugestões devem ser preventivas e técnicas.
Não invente falhas que não possam ser relacionadas aos dados.

Responda em português.
"""
    },
    {
        "role": "user",
        "content": f"""
Analise os dados atuais da nave Aurora Siger:

{dados_formatados}
"""
    }
]


# ==========================================================
# 11. EXECUÇÃO DO MODELO DE IA
# ==========================================================

texto = tokenizer.apply_chat_template(
    mensagens,
    tokenize=False,
    add_generation_prompt=True
)

entradas = tokenizer(
    texto,
    return_tensors="pt"
).to(model.device)

with torch.no_grad():
    saida = model.generate(
        **entradas,
        max_new_tokens=500,
        temperature=0.2,
        do_sample=True,
        top_p=0.9
    )

resposta = tokenizer.decode(
    saida[0][entradas["input_ids"].shape[1]:],
    skip_special_tokens=True
)


# ==========================================================
# 12. RESULTADO DA IA
# ==========================================================

print()
print("=" * 60)
print("12. ANÁLISE DA INTELIGÊNCIA ARTIFICIAL")
print("=" * 60)
print()

print(resposta)

============================================================
6. TELEMETRIA DA AURORA SIGER
============================================================

                Parâmetro   Valor Unidade
0     Temperatura interna   17.56      °C
1     Temperatura externa   48.03      °C
2  Integridade estrutural       1
3        Nível de energia   88.58       %
4     Pressão dos tanques  101.45
5        Módulos críticos   FALHA
6       Status do sistema     NOK

DIAGNÓSTICO DA TELEMETRIA
------------------------------------------------------------
Foram identificadas condições que exigem atenção.

Falhas identificadas:
- Pressão dos tanques
- Módulos críticos

============================================================
8. ANÁLISE ENERGÉTICA
============================================================

            Parâmetro  Valor Unidade
0  Energia disponível  36.91     kWh
1  Perdas energéticas   2.57     kWh
2        Energia útil  34.33     kWh
3  Autonomia estimada   0.95       h
4    Autonomia mínima    2.0       h
5   Status energético    NOK

DIAGNÓSTICO ENERGÉTICO
------------------------------------------------------------
A condição energética apresenta insuficiência de autonomia.